export const copy = {
  home: {
    appName: 'unrealDice',
    eyebrow: 'Local-first dice companion',
    mainMenuLabel: 'Main menu',
    subtitle: 'Offline dice tools for tabletop and quick decisions.',
    footerNote:
      'Designed for offline use. Saved groups will remain local to this device.',
    actions: [
      { label: 'Quick Start', path: '/quick-start' },
      { label: 'Create Group', path: '/groups/new' },
      { label: 'My Groups', path: '/groups' },
      { label: 'Import Backup', path: '/import' },
      { label: 'Coin & Random', path: '/random' },
      { label: 'Install App', path: '/install' },
    ],
  },
  placeholders: [
    { title: 'Create Group', path: '/groups/new' },
    { title: 'Import Backup', path: '/import' },
    { title: 'Coin & Random', path: '/random' },
    { title: 'Install App', path: '/install' },
  ],
  quickStart: {
    eyebrow: 'Read-only templates',
    title: 'Quick Start',
    description: 'Copy a built-in dice group into My Groups, or open its future Play Mode placeholder.',
    setsLabel: (count: number) => `${count} ${count === 1 ? 'set' : 'sets'}`,
    actions: {
      play: 'Play',
      copy: 'Copy',
      myGroups: 'Go to My Groups',
      backHome: 'Back to Home',
    },
    feedback: {
      copied: (groupName: string) => `${groupName} was added to My Groups.`,
    },
    errors: {
      maxGroupsReached: 'The saved group limit has been reached. Delete a group before copying another template.',
      copyFailed: 'The template could not be copied. Please try again.',
    },
  },
  myGroups: {
    eyebrow: 'Local groups',
    title: 'My Groups',
    description: 'Manage the groups saved on this device.',
    emptyTitle: 'No saved groups yet.',
    emptyDescription: 'Copy a Quick Start template or create your own group to begin.',
    setsLabel: (count: number) => `${count} ${count === 1 ? 'set' : 'sets'}`,
    combosLabel: (count: number) => `${count} ${count === 1 ? 'combo' : 'combos'}`,
    sourceLabels: {
      user: 'Created group',
      'quick-start': 'Quick Start template',
      'quick-start-copy': 'Copied template',
      imported: 'Imported group',
    },
    actions: {
      quickStart: 'Quick Start',
      createGroup: 'Create Group',
      play: 'Play',
      edit: 'Edit',
      export: 'Export',
      delete: 'Delete',
      backHome: 'Back to Home',
    },
    exportUnavailableLabel: 'Export will be available in a later phase.',
    deleteDialog: {
      title: 'Delete saved group',
      message: (groupName: string) =>
        `Delete "${groupName}"? This saved group will be removed from this device.`,
      confirm: 'Delete',
      cancel: 'Cancel',
    },
    feedback: {
      deleted: 'The saved group was deleted.',
      exportUnavailable: 'Export will be available in a later phase.',
    },
  },
  groupFeaturePlaceholder: {
    playEyebrow: 'Play Mode',
    editEyebrow: 'Group Editor',
    playQuickStartMessage: 'Play Mode for this Quick Start template will be implemented in a later phase.',
    playGroupMessage: 'Play Mode for this saved group will be implemented in a later phase.',
    editGroupMessage: 'The Group Editor will be implemented in the next phase.',
    missingGroupTitle: 'Group not found',
    missingGroupMessage: 'This group is not available on this device.',
    back: 'Back',
  },
  lockedDiceCountingLabels: {
    include: 'Locked dice included in total',
    exclude: 'Locked dice excluded from total',
  },
  laterPhase: 'Later phase',
  placeholderMessage: 'This feature will be implemented in a later phase.',
  backToHome: 'Back to Home',
} as const
