export const copy = {
  home: {
    appName: 'unrealDice',
    eyebrow: 'Local-first dice companion',
    mainMenuLabel: 'Main menu',
    subtitle: 'Offline dice tools for tabletop and quick decisions.',
    footerNote:
      'Designed for offline use. Saved groups will remain local to this device.',
    actions: [
      { label: 'Quick Start', path: '/quick-start' },
      { label: 'Create Group', path: '/groups/new' },
      { label: 'My Groups', path: '/groups' },
      { label: 'Import Backup', path: '/import' },
      { label: 'Coin & Random', path: '/random' },
      { label: 'Install App', path: '/install' },
    ],
  },
  placeholders: [
    { title: 'Install App', path: '/install' },
  ],
  quickStart: {
    eyebrow: 'Read-only templates',
    title: 'Quick Start',
    description: 'Copy a built-in dice group into My Groups, or open its future Play Mode placeholder.',
    setsLabel: (count: number) => `${count} ${count === 1 ? 'set' : 'sets'}`,
    actions: {
      play: 'Play',
      copy: 'Copy',
      myGroups: 'Go to My Groups',
      backHome: 'Back to Home',
    },
    feedback: {
      copied: (groupName: string) => `${groupName} was added to My Groups.`,
    },
    errors: {
      maxGroupsReached: 'The saved group limit has been reached. Delete a group before copying another template.',
      copyFailed: 'The template could not be copied. Please try again.',
    },
  },
  myGroups: {
    eyebrow: 'Local groups',
    title: 'My Groups',
    description: 'Manage the groups saved on this device.',
    emptyTitle: 'No saved groups yet.',
    emptyDescription: 'Copy a Quick Start template or create your own group to begin.',
    setsLabel: (count: number) => `${count} ${count === 1 ? 'set' : 'sets'}`,
    combosLabel: (count: number) => `${count} ${count === 1 ? 'combo' : 'combos'}`,
    sourceLabels: {
      user: 'Created group',
      'quick-start': 'Quick Start template',
      'quick-start-copy': 'Copied template',
      imported: 'Imported group',
    },
    actions: {
      quickStart: 'Quick Start',
      createGroup: 'Create Group',
      play: 'Play',
      edit: 'Edit',
      export: 'Export',
      exportAll: 'Export All Groups',
      delete: 'Delete',
      backHome: 'Back to Home',
    },
    exportGroupLabel: (groupName: string) => `Export ${groupName}`,
    exportAllLabel: 'Export all saved groups',
    deleteDialog: {
      title: 'Delete saved group',
      message: (groupName: string) =>
        `Delete "${groupName}"? This saved group will be removed from this device.`,
      confirm: 'Delete',
      cancel: 'Cancel',
    },
    feedback: {
      deleted: 'The saved group was deleted.',
      exported: (fileName: string) => `${fileName} was created.`,
    },
  },
  backup: {
    exportDialog: {
      titleSingle: 'Export Group',
      titleAll: 'Export All Groups',
      messageSingle: (groupName: string) =>
        `Export "${groupName}" as a JSON backup file?`,
      messageAll: (count: number) =>
        `Export ${count} saved ${count === 1 ? 'group' : 'groups'} as one JSON backup file?`,
      confirm: 'Export',
      cancel: 'Cancel',
    },
    importScreen: {
      eyebrow: 'Local JSON backup',
      title: 'Import Backup',
      description: 'Choose an unrealDice backup file to import saved groups.',
      warning:
        'unrealDice stores your groups locally on this device. Your data can be lost if browser data is cleared, the app is removed, private browsing is used, or the device is reset. Export a backup if your saved groups are important to you.',
      fileLabel: 'Backup JSON file',
      fileHint: 'Choose an unrealDice backup file to import saved groups.',
      validMessage: (count: number, exportType: string) =>
        `Valid ${exportType} backup with ${count} ${count === 1 ? 'group' : 'groups'} found.`,
      success: (count: number) =>
        `${count} imported ${count === 1 ? 'group was' : 'groups were'} added to My Groups.`,
      actions: {
        import: 'Import',
        back: 'Back to Home',
        myGroups: 'Go to My Groups',
      },
      errors: {
        readFailed: 'The selected file could not be read.',
        noValidBackup: 'Choose a valid backup before importing.',
        maxGroupsReached:
          'There is not enough room to import all groups. Delete saved groups first.',
        saveFailed: 'The imported groups could not be saved.',
      },
    },
    importConfirm: {
      title: 'Import Backup',
      message: (count: number) =>
        `Import ${count} ${count === 1 ? 'group' : 'groups'} into My Groups? Imported groups will be saved as new editable copies on this device.`,
      confirm: 'Import',
      cancel: 'Cancel',
    },
  },
  random: {
    menu: {
      eyebrow: 'Quick random tools',
      title: 'Coin & Random',
      description: 'Use a quick coin flip or generate a random number.',
      coinAction: 'Heads / Tails',
      maxLabel: 'Maximum number',
      startNumber: 'Start Random Number',
      backHome: 'Back to Home',
      errors: {
        max: 'Enter a whole number from 2 to 100.',
      },
    },
    coin: {
      title: 'Heads / Tails',
      instruction: 'Tap the coin to flip. Long press or double-click to view history.',
      tokenLabel: 'Flip coin',
      historyAction: 'History',
      back: 'Back to Coin & Random',
      history: {
        title: 'Heads / Tails History',
        clearMessage: 'Clear Heads / Tails history? This cannot be undone.',
      },
    },
    number: {
      title: (max: number) => `Random 1-${max}`,
      instruction: 'Tap to generate a number. Long press or double-click to view history.',
      tokenLabel: (max: number) => `Generate random number from 1 to ${max}`,
      historyAction: 'History',
      back: 'Back to Coin & Random',
      history: {
        title: 'Random Number History',
        range: (min: number, max: number) => `Range ${min}-${max}`,
        clearMessage: 'Clear Random Number history? This cannot be undone.',
      },
    },
    history: {
      empty: 'No results yet.',
      clearHistory: 'Clear History',
      clear: 'Clear',
      cancel: 'Cancel',
      close: 'Close',
    },
  },
  groupEditor: {
    createTitle: 'Create Group',
    editTitle: 'Edit Group',
    description: 'Build a local dice group from configurable set slots.',
    notFoundTitle: 'Group not found',
    notFoundMessage: 'This saved group is not available on this device.',
    form: {
      groupName: 'Group name',
      lockedDiceCounting: 'Locked Dice Counting',
      initialSlots: 'Initial set slots',
      setSlots: 'Set slots',
      excludeLockedDice: 'Exclude locked dice from total',
      includeLockedDice: 'Include locked dice in total',
    },
    actions: {
      help: 'Help',
      createSlots: 'Apply slot count',
      addSet: 'Add Set',
      addCombo: 'Add Combo',
      save: 'Save',
      saveAndPlay: 'Save & Play',
      cancel: 'Cancel',
      backToGroups: 'Back to My Groups',
    },
    errors: {
      slotCount: (max: number) => `Enter a set slot count from 1 to ${max}.`,
      maxSetsReached: (max: number) => `A group cannot contain more than ${max} set slots.`,
      maxGroupsReached: 'The saved group limit has been reached. Delete a group before creating another.',
      saveFailed: 'The group could not be saved. Please check the fields and try again.',
    },
    confirmations: {
      reduceSlotsTitle: 'Reduce set slots',
      reduceSlotsMessage: 'Reducing the slot count will discard configured sets. Continue?',
      removeSetTitle: 'Remove set',
      removeSetMessage: (setName: string) => `Remove "${setName}" from this group?`,
      deleteComboTitle: 'Delete combo',
      deleteComboMessage: (comboName: string) =>
        `Delete "${comboName}"? Its sets will remain in this group.`,
      emptySlotsTitle: 'Ignore empty slots',
      emptySlotsMessage: 'Empty set slots will be ignored when this group is saved. Continue?',
      overwriteTitle: 'Save changes',
      overwriteMessage: (groupName: string) =>
        `Save changes to "${groupName}"? This will replace the previously saved configuration.`,
      unsavedTitle: 'Unsaved changes',
      unsavedMessage: 'You have unsaved changes. Discard them?',
      confirm: 'Continue',
      save: 'Save changes',
      remove: 'Remove',
      delete: 'Delete',
      discard: 'Discard',
      cancel: 'Cancel',
    },
    help: {
      title: 'Group setup help',
      close: 'Close',
      items: [
        'A group contains the sets used together in a game.',
        'A set represents one dice type and amount, for example 5d6.',
        'All dice inside one set use the same number of sides.',
        'A set can be customized with dice and pip/number colors.',
        'Locked Dice Counting decides whether locked dice will count toward totals during play.',
        'Combos group multiple sets so they can later be rolled together in Play Mode.',
        'Groups are stored locally after saving.',
      ],
    },
    setSlot: {
      empty: 'Empty Set',
      comboLabel: (comboName: string) => `Combo: ${comboName}`,
      configure: 'Configure',
      edit: 'Edit',
      remove: 'Remove',
      preview: 'Set preview',
    },
    combos: {
      title: 'Combos',
      empty: 'No combos yet.',
      noConfiguredSets: 'Configure at least one set before creating a combo.',
      includedSets: 'Included sets',
      emptyWarning: 'No sets selected. Edit or delete this combo before saving.',
      edit: 'Edit',
      delete: 'Delete',
      colorSwatch: (comboName: string) => `${comboName} color`,
    },
    comboDialog: {
      titleNew: 'Create Combo',
      titleEdit: 'Edit Combo',
      fields: {
        name: 'Combo name',
        color: 'Combo color',
        sets: 'Select sets',
      },
      selected: 'Selected',
      notSelected: 'Not selected',
      moveTitle: 'Move set to this combo',
      moveMessage: (setName: string, fromComboName: string, toComboName: string) =>
        `"${setName}" already belongs to "${fromComboName}". Move it to "${toComboName}"?`,
      moveSet: 'Move Set',
      errors: {
        name: 'Combo name is required.',
        duplicateName: 'Combo name must be unique inside this group.',
        color: 'Combo color is required.',
        sets: 'Select at least one configured set.',
        maxSets: (max: number) => `A combo cannot contain more than ${max} sets.`,
        maxCombos: (max: number) => `A group cannot contain more than ${max} combos.`,
        duplicateAssignment: 'A set can belong to only one combo.',
      },
      confirm: 'Confirm Combo',
      cancel: 'Cancel',
    },
    setDialog: {
      titleNew: 'Configure Set',
      titleEdit: 'Edit Set',
      fields: {
        name: 'Set name',
        diceCount: 'Number of dice',
        sides: 'Sides per die',
        diceColor: 'Dice body color',
        pipColor: 'Number / dot color',
      },
      optionalNameHint: 'Optional. A default name is used if this is empty.',
      errors: {
        diceCount: (max: number) => `Enter an integer from 1 to ${max}.`,
        sides: (min: number, max: number) => `Enter an integer from ${min} to ${max}.`,
        diceColor: 'Choose a dice body color.',
        pipColor: 'Choose a number / dot color.',
      },
      save: 'Save Set',
      cancel: 'Cancel',
    },
  },
  groupFeaturePlaceholder: {
    playEyebrow: 'Play Mode',
    editEyebrow: 'Group Editor',
    playQuickStartMessage: 'Play Mode for this Quick Start template will be implemented in a later phase.',
    playGroupMessage: 'Play Mode for this saved group will be implemented in a later phase.',
    editGroupMessage: 'The Group Editor will be implemented in the next phase.',
    missingGroupTitle: 'Group not found',
    missingGroupMessage: 'This group is not available on this device.',
    back: 'Back',
  },
  lockedDiceCountingLabels: {
    include: 'Locked dice included in total',
    exclude: 'Locked dice excluded from total',
  },
  laterPhase: 'Later phase',
  placeholderMessage: 'This feature will be implemented in a later phase.',
  backToHome: 'Back to Home',
} as const
