export const copy = {
  home: {
    appName: 'unrealDice',
    eyebrow: 'created by STUdevil',
    mainMenuLabel: 'Main menu',
    subtitle: 'Offline dice tools for tabletop and quick decisions.',
    footerNote:
      'Designed for offline use. Saved groups will remain local to this device.',
    actions: [
      { label: 'Quick Start', path: '/quick-start' },
      { label: 'Create Group', path: '/groups/new' },
      { label: 'My Groups', path: '/groups' },
      { label: 'Import Backup', path: '/import' },
      { label: 'Coin & Random', path: '/random' },
      { label: 'Install App', path: '/install' },
    ],
  },
  quickStart: {
    eyebrow: 'Read-only templates',
    title: 'Quick Start',
    description: 'Play a built-in dice group or copy it into My Groups for editing.',
    setsLabel: (count: number) => `${count} ${count === 1 ? 'set' : 'sets'}`,
    actions: {
      play: 'Play',
      copy: 'Copy',
      myGroups: 'Go to My Groups',
      backHome: 'Back to Home',
    },
    feedback: {
      copied: (groupName: string) => `${groupName} was added to My Groups.`,
    },
    loading: 'Loading Quick Start templates.',
    remoteFallback: (source: 'remote' | 'cache' | 'built-in') =>
      source === 'cache'
        ? 'Remote templates are unavailable. Showing the last cached templates.'
        : 'Remote templates are unavailable. Showing built-in templates.',
    errors: {
      maxGroupsReached: 'The saved group limit has been reached. Delete a group before copying another template.',
      copyFailed: 'The template could not be copied. Please try again.',
    },
  },
  myGroups: {
    eyebrow: 'Local groups',
    title: 'My Groups',
    description: 'Manage the groups saved on this device.',
    emptyTitle: 'No saved groups yet.',
    emptyDescription: 'Copy a Quick Start template or create your own group to begin.',
    setsLabel: (count: number) => `${count} ${count === 1 ? 'set' : 'sets'}`,
    combosLabel: (count: number) => `${count} ${count === 1 ? 'combo' : 'combos'}`,
    sourceLabels: {
      user: 'Created group',
      'quick-start': 'Quick Start template',
      'quick-start-copy': 'Copied template',
      imported: 'Imported group',
    },
    actions: {
      quickStart: 'Quick Start',
      createGroup: 'Create Group',
      play: 'Play',
      edit: 'Edit',
      export: 'Export',
      exportAll: 'Export All Groups',
      delete: 'Delete',
      backHome: 'Back to Home',
    },
    exportGroupLabel: (groupName: string) => `Export ${groupName}`,
    exportAllLabel: 'Export all saved groups',
    deleteDialog: {
      title: 'Delete saved group',
      message: (groupName: string) =>
        `Delete "${groupName}"? This saved group will be removed from this device.`,
      confirm: 'Delete',
      cancel: 'Cancel',
    },
    feedback: {
      deleted: 'The saved group was deleted.',
      exported: (fileName: string) => `${fileName} was created.`,
    },
  },
  backup: {
    exportDialog: {
      titleSingle: 'Export Group',
      titleAll: 'Export All Groups',
      messageSingle: (groupName: string) =>
        `Export "${groupName}" as a JSON backup file?`,
      messageAll: (count: number) =>
        `Export ${count} saved ${count === 1 ? 'group' : 'groups'} as one JSON backup file?`,
      confirm: 'Export',
      cancel: 'Cancel',
    },
    importScreen: {
      eyebrow: 'Local JSON backup',
      title: 'Import Backup',
      description: 'Choose an unrealDice backup file to import saved groups.',
      warning:
        'unrealDice stores your groups locally on this device. Your data can be lost if browser data is cleared, the app is removed, private browsing is used, or the device is reset. Export a backup if your saved groups are important to you.',
      fileLabel: 'Backup JSON file',
      fileHint: 'Choose an unrealDice backup file to import saved groups.',
      validMessage: (count: number, exportType: string) =>
        `Valid ${exportType} backup with ${count} ${count === 1 ? 'group' : 'groups'} found.`,
      success: (count: number) =>
        `${count} imported ${count === 1 ? 'group was' : 'groups were'} added to My Groups.`,
      actions: {
        import: 'Import',
        back: 'Back to Home',
        myGroups: 'Go to My Groups',
      },
      errors: {
        readFailed: 'The selected file could not be read.',
        noValidBackup: 'Choose a valid backup before importing.',
        maxGroupsReached:
          'There is not enough room to import all groups. Delete saved groups first.',
        saveFailed: 'The imported groups could not be saved.',
      },
    },
    importConfirm: {
      title: 'Import Backup',
      message: (count: number) =>
        `Import ${count} ${count === 1 ? 'group' : 'groups'} into My Groups? Imported groups will be saved as new editable copies on this device.`,
      confirm: 'Import',
      cancel: 'Cancel',
    },
  },
  random: {
    menu: {
      eyebrow: 'Quick random tools',
      title: 'Coin & Random',
      description: 'Use a quick coin flip or generate a random number.',
      coinAction: 'Heads / Tails',
      maxLabel: 'Maximum number',
      startNumber: 'Start Random Number',
      backHome: 'Back to Home',
      errors: {
        max: 'Enter a whole number from 2 to 100.',
      },
    },
    coin: {
      title: 'Heads / Tails',
      instruction: 'Tap the coin to flip. Long press or double-click to view history.',
      tokenLabel: 'Flip coin',
      back: 'Back to Coin & Random',
      history: {
        title: 'Heads / Tails History',
        clearMessage: 'Clear Heads / Tails history? This cannot be undone.',
      },
    },
    number: {
      title: (max: number) => `Random 1-${max}`,
      instruction: 'Tap to generate a number. Long press or double-click to view history.',
      tokenLabel: (max: number) => `Generate random number from 1 to ${max}`,
      back: 'Back to Coin & Random',
      history: {
        title: 'Random Number History',
        range: (min: number, max: number) => `Range ${min}-${max}`,
        clearMessage: 'Clear Random Number history? This cannot be undone.',
      },
    },
    history: {
      empty: 'No results yet.',
      clearHistory: 'Clear History',
      clear: 'Clear',
      cancel: 'Cancel',
      close: 'Close',
    },
  },
  install: {
    eyebrow: 'Offline app',
    title: 'Install unrealDice',
    description: 'Install unrealDice on your device for quick access and offline use.',
    status: {
      installed: 'unrealDice is installed on this device.',
      promptAvailable: 'Your browser can install unrealDice on this device.',
      manual: 'Use the instructions below to add unrealDice to your device.',
    },
    actions: {
      install: 'Install App',
      backHome: 'Back to Home',
    },
    instructions: [
      {
        title: 'Android / Chrome',
        steps: [
          'Open unrealDice in Chrome.',
          'Open the browser menu.',
          'Choose Install app or Add to Home screen.',
          'Open unrealDice from your home screen once while online.',
        ],
      },
      {
        title: 'iPhone / Safari',
        steps: [
          'Open unrealDice in Safari.',
          'Tap the Share button.',
          'Choose Add to Home Screen.',
          'Open unrealDice from your home screen once while online.',
        ],
      },
      {
        title: 'Desktop',
        steps: [
          'Open unrealDice in a compatible browser.',
          'Use the install icon or browser install option when shown.',
          'Launch unrealDice like a normal app.',
        ],
      },
    ],
    offlineWarning:
      'After unrealDice has been loaded and cached, core app features can work offline. Your saved groups and histories are stored locally on this device/browser. They can be lost if you clear browser data, remove the app, use private browsing, or reset the device. Export backups for groups you want to protect.',
    update: {
      message: 'A new version of unrealDice is available.',
      action: 'Update now',
    },
  },
  studio: {
    eyebrow: 'Private studio',
    loading: 'Loading studio.',
    unavailable: {
      title: 'Studio setup unavailable',
      message:
        'Supabase is not configured. The public app still works with built-in Quick Start templates.',
    },
    offline: {
      title: 'Studio requires internet',
      message: 'Studio management requires an internet connection.',
    },
    login: {
      title: 'Studio Sign In',
      description: 'Sign in with the configured Supabase admin account.',
      email: 'Email',
      password: 'Password',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
    },
    templates: {
      title: 'Quick Start Templates',
      description: 'Manage remote public templates protected by Supabase Auth and RLS.',
      emptyTitle: 'No remote templates visible.',
      emptyDescription: 'Create a template or verify that the signed-in user is authorized.',
    },
    editor: {
      createTitle: 'New Quick Start Template',
      editTitle: 'Edit Quick Start Template',
      description: 'Configure the template that can be published to public Quick Start.',
    },
    fields: {
      name: 'Template name',
      templateKey: 'Template key',
      sortOrder: 'Display order',
      published: 'Published',
    },
    status: {
      published: 'Published',
      hidden: 'Hidden / Draft',
    },
    actions: {
      newTemplate: 'New Template',
      edit: 'Edit',
      publish: 'Publish',
      unpublish: 'Unpublish',
      delete: 'Delete',
      signOut: 'Sign Out',
      save: 'Save Template',
      cancel: 'Cancel',
    },
    deleteDialog: {
      title: 'Delete template',
      message: (templateName: string) =>
        `Delete "${templateName}"? This removes it from the public template collection.`,
    },
    errors: {
      loadFailed: 'Templates could not be loaded. Check Supabase access and RLS policies.',
      saveFailed: 'The template could not be saved.',
      deleteFailed: 'The template could not be deleted.',
      invalidTemplate: 'This remote template contains invalid data.',
    },
  },
  play: {
    loading: 'Loading playable group.',
    eyebrow: 'Play Mode',
    notFoundTitle: 'Group not found',
    notFoundMessage: 'This playable group is not available on this device.',
    actions: {
      rollAll: 'Roll All',
      rollAllTotal: (total: number) => `Roll All · Total ${total}`,
      rollSet: (setName: string) => `Roll ${setName}`,
      comboTotal: (comboName: string, total: number) => `${comboName} · Total ${total}`,
      backQuickStart: 'Back to Quick Start',
      backMyGroups: 'Back to My Groups',
      copyBeforeCombos: 'Copy this template before adding combos',
      groupSetup: 'Group Setup',
      copyToEdit: 'Copy to Edit',
      help: 'Help',
      modifierSetup: 'Modifier Setup',
      turnModifierOn: 'Turn Modifier On',
      turnModifierOff: 'Turn Modifier Off',
      setSetup: 'Set Setup',
      close: 'Close',
      clearHistory: 'Clear History',
      clear: 'Clear',
      cancel: 'Cancel',
    },
    history: {
      title: (setName: string) => `${setName} History`,
      empty: 'No rolls yet.',
      total: (total: number) => `Total ${total}`,
      included: 'Locked dice included',
      excluded: 'Locked dice excluded',
      modifierOff: 'Modifier off',
      clearMessage: (setName: string) =>
        `Clear history for "${setName}"? This cannot be undone.`,
    },
    help: {
      title: 'Play Help',
      items: [
        'Tap a large set die to expand or collapse its individual dice. Sets with only one die show that die immediately instead of a large set die.',
        'Press a set Roll button to roll only that set. Use Roll All to roll every set in the group.',
        'Use combo buttons to roll only the sets that belong to that combo.',
        'Double-click or long press a large set die to open the set menu. The set menu contains History, Set Setup, Modifier Setup, and set-total modifier on/off when available.',
        'For sets with one die, use the set name to open that set menu.',
        'Expand a set, then double-click or long press an individual die to cycle its state.',
        'A normal die uses the configured set color. A modifier-active die is lighter. A locked die is darker.',
        'A large set die becomes lighter when any modifier is active, darker when locked dice are present, and diagonally split when both are true.',
        'Each Die modifiers apply the configured operation to every modifier-active individual die. Each die can cycle between modifier-active, normal, and locked.',
        'Set Total modifiers apply once to the set total. They start turned on and can be turned on or off from the set menu.',
        'Division modifiers always round up to the next whole number.',
        'Individual dice can be locked before the first roll. Locked empty dice stay unrolled until unlocked.',
        'Locked dice keep their current value during later rolls. They cannot be modifier-active at the same time.',
        'Whether locked dice count toward totals depends on this group’s Locked Dice Counting setting.',
      ],
    },
    labels: {
      toggleSet: (setName: string, state: string) =>
        `Expand or collapse ${setName} dice. Current set state: ${state}.`,
      toggleDie: (setName: string, dieNumber: number, mode: string) =>
        `Cycle ${setName} die ${dieNumber}. Current state: ${mode}.`,
      openSetMenu: (setName: string) => `Open ${setName} set menu.`,
    },
  },
  groupEditor: {
    createTitle: 'Create Group',
    editTitle: 'Edit Group',
    description: 'Build a local dice group from configurable set slots.',
    notFoundTitle: 'Group not found',
    notFoundMessage: 'This saved group is not available on this device.',
    form: {
      groupName: 'Group name',
      lockedDiceCounting: 'Locked Dice Counting',
      initialSlots: 'Initial set slots',
      setSlots: 'Set slots',
      excludeLockedDice: 'Exclude locked dice from total',
      includeLockedDice: 'Include locked dice in total',
    },
    actions: {
      help: 'Help',
      createSlots: 'Apply slot count',
      addSet: 'Add Set',
      addCombo: 'Add Combo',
      save: 'Save',
      saveAndPlay: 'Save & Play',
      cancel: 'Cancel',
      backToGroups: 'Back to My Groups',
    },
    errors: {
      slotCount: (max: number) => `Enter a set slot count from 1 to ${max}.`,
      maxSetsReached: (max: number) => `A group cannot contain more than ${max} set slots.`,
      maxGroupsReached: 'The saved group limit has been reached. Delete a group before creating another.',
      saveFailed: 'The group could not be saved. Please check the fields and try again.',
    },
    confirmations: {
      reduceSlotsTitle: 'Reduce set slots',
      reduceSlotsMessage: 'Reducing the slot count will discard configured sets. Continue?',
      removeSetTitle: 'Remove set',
      removeSetMessage: (setName: string) => `Remove "${setName}" from this group?`,
      deleteComboTitle: 'Delete combo',
      deleteComboMessage: (comboName: string) =>
        `Delete "${comboName}"? Its sets will remain in this group.`,
      emptySlotsTitle: 'Ignore empty slots',
      emptySlotsMessage: 'Empty set slots will be ignored when this group is saved. Continue?',
      overwriteTitle: 'Save changes',
      overwriteMessage: (groupName: string) =>
        `Save changes to "${groupName}"? This will replace the previously saved configuration.`,
      unsavedTitle: 'Unsaved changes',
      unsavedMessage: 'You have unsaved changes. Discard them?',
      confirm: 'Continue',
      save: 'Save changes',
      remove: 'Remove',
      delete: 'Delete',
      discard: 'Discard',
      cancel: 'Cancel',
    },
    help: {
      title: 'Group setup help',
      close: 'Close',
      items: [
        'A group contains the sets used together in a game.',
        'A set represents one dice type and amount, for example 5d6.',
        'All dice inside one set use the same number of sides.',
        'A set can be customized with dice and pip/number colors.',
        'Locked Dice Counting decides whether locked dice will count toward totals during play.',
        'Combos group multiple sets so they can later be rolled together in Play Mode.',
        'Groups are stored locally after saving.',
      ],
    },
    setSlot: {
      empty: 'Empty Set',
      comboLabel: (comboName: string) => `Combo: ${comboName}`,
      configure: 'Configure',
      edit: 'Edit',
      remove: 'Remove',
      preview: 'Set preview',
    },
    combos: {
      title: 'Combos',
      empty: 'No combos yet.',
      noConfiguredSets: 'Configure at least one set before creating a combo.',
      includedSets: 'Included sets',
      emptyWarning: 'No sets selected. Edit or delete this combo before saving.',
      edit: 'Edit',
      delete: 'Delete',
      colorSwatch: (comboName: string) => `${comboName} color`,
    },
    comboDialog: {
      titleNew: 'Create Combo',
      titleEdit: 'Edit Combo',
      fields: {
        name: 'Combo name',
        color: 'Combo color',
        sets: 'Select sets',
      },
      selected: 'Selected',
      notSelected: 'Not selected',
      moveTitle: 'Move set to this combo',
      moveMessage: (setName: string, fromComboName: string, toComboName: string) =>
        `"${setName}" already belongs to "${fromComboName}". Move it to "${toComboName}"?`,
      moveSet: 'Move Set',
      errors: {
        name: 'Combo name is required.',
        duplicateName: 'Combo name must be unique inside this group.',
        color: 'Combo color is required.',
        sets: 'Select at least one configured set.',
        maxSets: (max: number) => `A combo cannot contain more than ${max} sets.`,
        maxCombos: (max: number) => `A group cannot contain more than ${max} combos.`,
        duplicateAssignment: 'A set can belong to only one combo.',
      },
      confirm: 'Confirm Combo',
      cancel: 'Cancel',
    },
    setDialog: {
      titleNew: 'Configure Set',
      titleEdit: 'Edit Set',
      fields: {
        name: 'Set name',
        diceCount: 'Number of dice',
        sides: 'Sides per die',
        diceColor: 'Dice body color',
        pipColor: 'Number / dot color',
        enableModifier: 'Enable Modifier',
        modifierOperator: 'Modifier operation',
        modifierValue: 'Modifier value',
        modifierApplication: 'Apply modifier',
        eachDie: 'Each Die',
        setTotal: 'Set Total',
      },
      modifierHelp:
        'Apply a modifier to each die separately or once to the set total. Division rounds up.',
      modifierSummary: {
        eachDie: (operator: string, value: number) => `${operator}${value} each die`,
        setTotal: (operator: string, value: number) => `${operator}${value} on total`,
      },
      operators: {
        add: '+',
        subtract: '-',
        multiply: '×',
        divide: '÷',
      },
      optionalNameHint: 'Optional. A default name is used if this is empty.',
      contrastWarning:
        'These colors may be difficult to read together. Choose stronger contrast if this set will be used often.',
      errors: {
        diceCount: (max: number) => `Enter an integer from 1 to ${max}.`,
        sides: (min: number, max: number) => `Enter an integer from ${min} to ${max}.`,
        diceColor: 'Choose a dice body color.',
        pipColor: 'Choose a number / dot color.',
        modifierValue: 'Enter an integer from 1 to 100.',
      },
      save: 'Save Set',
      cancel: 'Cancel',
    },
  },
  lockedDiceCountingLabels: {
    include: 'Locked dice included in total',
    exclude: 'Locked dice excluded from total',
  },
  notFound: {
    eyebrow: 'Route not found',
    title: 'Nothing here',
    message: 'This page does not exist in unrealDice.',
  },
  backToHome: 'Back to Home',
} as const
